### ISSUE TITLE
Global variables?

### ISSUE THREAD

**Issue by duzenko** [coolchyni/beyond-debug#10]
Is there a problem with displaying global variables?

E.g. 
```
var
    i: integer;
begin
    for i:= 1 to 10 do
        WriteLn(i);
end.
```

With breakpoint on `WriteLn(i);` there is no way to see the global variable `i` or any other global variable for that matter

![image](https://github.com/coolchyni/beyond-debug/assets/1481807/6f419fe6-e72e-495c-a539-1092e666e886)

**Comment by xuming** [comment]
Global variables is not support ,you must add it to watch by your self.

**Comment by duzenko** [comment]
Is there a particular reason for this?

**Comment by xuming** [comment]
There are too many global variables in the Pascal program.
