### ISSUE TITLE
Question about x64 assembly debugging

### ISSUE THREAD

**Issue by aressler38** [coolchyni/beyond-debug#4]
I am trying to use this extension to debug assembly, but I don't see any variables or register values show up in the debug panel. I am wondering if I need to use a special configuration or not. I was looking for something that works like [this other extension](https://github.com/damiankoper/vscode-gdb-debug) and is maintained. I am able to step through breakpoints, but I don't see any variables while stepping through.

Here's my launch.json
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "by-gdb",
            "request": "launch",
            "name": "Launch(gdb)",
            "program": "${workspaceFolder}/${fileBasenameNoExtension}",
            "cwd": "${workspaceRoot}",
            "preLaunchTask": "asm64",
        }
    ],
    "compounds": []
}
```

The asm64 task definition is as follows.
```
        {
            "label": "asm64",
            "type": "shell",
            "command": "rawfilename=${fileDirname}/${fileBasenameNoExtension}; nasm -F dwarf -g -f elf64 -i ${fileDirname} -o $rawfilename.o ${file}; ld -m elf_x86_64 -o $rawfilename $rawfilename.o;",
            "problemMatcher": {
                "pattern": {
                    "regexp": "error"
                }
            },
            "presentation": {
                "focus": true,
                "panel": "dedicated",
                "reveal": "silent",
                "clear": true
            }
        },
```

I'm running this on Windows and using the remote extension to open the project in WSL2 (Debian bullseye). 

![image](https://user-images.githubusercontent.com/2053500/206828233-4c8ad138-45d5-4e83-8066-e39293f1f048.png)

Am I using the extension incorrectly, or is it not intended for this use case?

**Comment by aressler38** [comment]
The main idea is to be able to debug the book xchg rax,rax, but I can't see anything yet.

**Comment by xuming** [comment]
Currently, displaying the registers in assembly is not supported, but it will be available in future versions. For now, you can view the values of the registers by typing "info registers" or "p $eax" in the DEBUG CONSOLE.

**Comment by aressler38** [comment]
@xuming Thanks for the tip!
